Kubernetes 2
veffhz/microservices pull request #12
Opened 2017-12-07 06:13 UTC by veffhz

Коллеги, доброе утро!

В этом пул-реквесте результаты выполнения домашнего задания 29 по Kubernetes 2:

    Deployment компоненты и объекты service сконфигурированы для запуска reddit в кластере Kubernetes (в каталоге kube_reddit).
    Приложение запущено в реальном кластере GKE.

![image](https://user-images.githubusercontent.com/8789364/33701192-b8df80ee-db2e-11e7-8526-32ba609ac85f.png)
    
Ссылка http://35.226.201.84:31653/

С уважением,
Владимир.

2017-12-07 10:04 UTC, chromko requested changes
Отделите, пожалуйста, compose и hard_way от этого дз.

2017-12-07 10:04 UTC, chromko commented on docker-compose.infra.yml
>    mongodb-exporter:
а compose сюда как влез ?)

2017-12-07 10:10 UTC, veffhz commented on docker-compose.infra.yml
>    mongodb-exporter:
Я делал этот бранч от кубернетес-1, т.к. тот не был вмерджен в мастер. Вечером поправлю, спасибо! )

2017-12-13 12:31 UTC, chromko approved these changes
Задание выполнено. Можно мержить

2017-12-13 13:04 UTC, merged